name: 'Fetch Upstream'
description: 'This is a GitHub Action that fetches the upstream and merges that to master when you open a PR.'
author: 'Brian Douglas'
inputs:
  upstream:
    description: 'The upstream for your fork'
    required: true
  upstream_branch:
    description: 'The upstream branch to fetch'
    required: false
    default: 'master'
  fork_branch:
    description: 'The branch in your fork to push to'
    required: false
    default: 'master'
  method:
    description: 'The merge method. "merge" or "rebase"'
    required: false
    default: 'merge'
runs:
  using: 'docker'
  image: 'Dockerfile'
